Repository coding-kkanbu/teameet_backend, pull requests merged in 2022-01, with the labels that each got.

#13 Update issue templates
  .github/ISSUE_TEMPLATE/docs.md
Labels: documentation

#12 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation

#17 Docs/settings
  CHANGELOG.rst
  README.rst
  local.yml
Labels: documentation, docker

#20 Update ci.yml
  .github/workflows/ci.yml
  CHANGELOG.md
  README.rst
Labels: bug

#24 Feat/swagger
  CHANGELOG.md
  CHANGELOG.rst
  README.rst
  config/settings/base.py
  config/urls.py
  requirements/base.txt
Labels: documentation

#25 Feat/new apps
  CHANGELOG.md
  config/settings/base.py
  kkanbu/board/__init__.py
  kkanbu/board/admin.py
  kkanbu/board/apps.py
  kkanbu/board/migrations/0001_initial.py
  kkanbu/board/migrations/__init__.py
  kkanbu/board/models.py
  kkanbu/board/tests.py
  kkanbu/board/views.py
  kkanbu/operation/__init__.py
  kkanbu/operation/admin.py
  kkanbu/operation/apps.py
  kkanbu/operation/migrations/0001_initial.py
  kkanbu/operation/migrations/__init__.py
  kkanbu/operation/models.py
  kkanbu/operation/tests.py
  kkanbu/operation/views.py
Labels: enhancement

#43 Feat/board/post update
  CHANGELOG.md
  kkanbu/board/migrations/0002_auto_20220125_2325.py
  kkanbu/board/models.py
  kkanbu/board/serializers.py
  kkanbu/board/urls.py
  kkanbu/board/views.py
Labels: documentation, enhancement
